# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d3423c9e1c6454edd8a439266171e0ea659f4a09da187b4c9dff072fcfe4f8e53ccdd57d78e758451db98e6336bd52c4f75d9d555166dee7bd49d4dcd30c5fca

test:
  secret_key_base: d5e2b8a4e86a076d93b08a2b058bdee5dee13f76da2c47c775085da28ade4418087b99da88e5005f546a5c9fe1429f1c53a3f018c8a75a524be94fc6ea6b0c85

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
